config/routes.rb
Tasker::Application.routes.draw do

  resources :projects do
    resources :tasks
  end

  root :to => 'projects#index'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	validates :name, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
 belongs_to :project
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

respond_to :html, :xml, :js

def index
   @projects = Project.all
   @project = Project.new
end

def show
    @project = Project.find(params[:id])

#    respond_to do |format|
#    format.html # show.html.erb
#      format.xml  { render :xml => @project }
#    end
end

  # GET /projects/new
  # GET /projects/new.xml
def new
  @project = Project.new

#  respond_to do |format|
#  format.html # new.html.erb
#  format.xml  { render :xml => @project }
#  end
end

  # GET /projects/1/edit
  # project /projects
  # project /projects.xml
  def create
    @project = Project.new(params[:project].permit(:name))
    @project.save
    redirect_to projects_path
#    respond_to do |format|
#      if @project.save
#        format.html { redirect_to(@project,
#                      :notice => 'project was successfully created.') }
#        format.xml  { render :xml => @project,
#                      :status => :created, :location => @project }
#      else
#        format.html { render :action => "new" }
#        format.xml  { render :xml => @project.errors,
#                      :status => :unprocessable_entity }
#      end
#    end
  end

  def edit
    @project = project.find(params[:id])

 end

 def update
  @project = Project.find(params[:id])
 
  if @project.update(params[:project].permit(:name))
    redirect_to projects_path
  else
    render 'edit'
  end
  end

  def destroy
  @project = Project.find(params[:id])
  @project.destroy
 
  redirect_to projects_path
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(params[:task].permit(:name, :completed))
    redirect_to projects_path
  end
  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to projects_path
  end
  def edit
   @project = Project.find(params[:project_id])
   @task = @project.tasks.find(params[:id])
 end

 def update
   @project = Project.find(params[:project_id])
   @task = @project.tasks.find(params[:id])
 
   redirect_to projects_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
   <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
   <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<h3>Editing project</h3>
 
<%= render 'form' %>
 
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1> TODO lists</h1>

<% @projects.each do |project| %>

<div class="project">

 <h2><%= project.name %></h2>
 <%= link_to 'Edit', edit_project_path(project) %>
      <%= link_to 'Destroy', project_path(project),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
  <% project.tasks.each do |task| %>

  <p><%= task.name %></p>
   <%= link_to 'Destroy Task', [task.project, task],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
         <%= link_to 'Edit Task', edit_project_task_path(task.project, task) %>

  <%= form_for ([project, project.tasks.build]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
  <% end %>
  <% end %>
<% end %>
</div>



<div>
<%= link_to 'New TODO list', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1>New todo list</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/tasks/edit.html.erb
<h3>Edit task</h3>
<%= form_for([@project, @project.tasks.build]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>